version: 2
sources:
  - name: marathon_raw
    schema: STAGING
    tables:
      - name: raw_runners
      - name: raw_results
models:
  - name: stg_runners
    access: public
  - name: stg_results
    access: public